version: '3'

services:
  web:
    build:
      context: ./api
      args:
        WEB_WORKDIR: $WEB_WORKDIR
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
    command: /bin/sh -c "rm -f /tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "$WEB_PORT:$WEB_PORT"
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - '3305:3305'
  front:
    build:
      context: ./front
      args:
        FRONT_WORKDIR: $FRONT_WORKDIR
    environment:
      BASE_URL: $BASE_URL
      BROWSER_BASE_URL: $BROWSER_BASE_URL
    volumes:
      - ./front:/app
    ports:
      - "$FRONT_PORT:$FRONT_PORT"
    tty: true
    stdin_open: true
    command: npm run dev

volumes:
  mysql_data:
  bundle: