version: '3'

services:
  web:
    build:
      context: ./api
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      API_DOMAIN: $API_DOMAIN
    command: /bin/sh -c "rm -f /tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql/
    ports:
      - '3307:3306'
  front:
    build:
      context: ./front
    environment:
      BASE_URL: $BASE_URL
      BROWSER_BASE_URL: $BROWSER_BASE_URL
    volumes:
      - ./front:/app
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    # command: npm run dev
    command: npm run start

volumes:
  mysql_data:
  bundle:
