# # Use the latest 2.1 version of CircleCI pipeline process engine.
# # See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1

# # Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# # See: https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   ruby: circleci/ruby@0.1.2

# # Define a job to be invoked later in a workflow.
# # See: https://circleci.com/docs/2.0/configuration-reference/#jobs
# jobs:
#   build:
#     docker:
#       - image: circleci/ruby:2.6.3-stretch-node
#     executor: ruby/default
#     steps:
#       - checkout
#       - run:
#           name: Which bundler?
#           command: bundle -v
#       - ruby/bundle-install

# # Invoke jobs via workflows
# # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
#   sample: # This is the name of the workflow, feel free to change it to better match your workflow.
#     # Inside the workflow, you define the jobs you want to run.
#     jobs:
#       - build



version:                     2.1

# 実行するjob
jobs:
  # buildするjob
  build:
    machine:
      image:                 circleci/classic:edge
    steps:
      - checkout
      - run:
          name:              docker-compose build
          command:           docker-compose build
  # testするjob
  test:
    machine:
      image:                 circleci/classic:edge
    steps:
      - checkout
      - run:
          name:              docker-compose up -d
          command:           docker-compose up -d
      - run:                 sleep 30
      # - run:
      #     name:              docker-compose run web rails db:create RAILS_ENV=test
      #     command:           docker-compose run web rails db:create RAILS_ENV=test
      # - run:
      #     name:              docker-compose run bk rails db:migrate RAILS_ENV=test
      #     command:           docker-compose run back rails db:migrate RAILS_ENV=test
      - run:
          name:              docker-compose run web bundle exec rspec spec
          command:           docker-compose run back bundle exec rspec spec
      - run:
          name:              docker-compose down
          command:           docker-compose down

# 順番を制御するworkflow
workflows:
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
