require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - vendor/*
    - bin/*
    - app/jobs/*
    - app/mailers/*
    - app/models/concerns/*
    - app/channels/**/*
    - config/**/*
    - db/migrate/*
    - db/schema.rb
    - lib/**/*
    - log/*
    - public/*
    - storage/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru

  NewCops: enable

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

Layout/LineLength:
  Max: 130


RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/SkipsModelValidations:
  Whitelist:
    - update_all

Style/ClassAndModuleChildren:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Security/Eval:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
