name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build
      shell: bash
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      run: 
        docker-compose build

    - name: up
      shell: bash
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      run: |
        docker-compose up -d

    # - name: sleep
    #   shell: bash
    #   run: |
    #     sleep 30

    # - name: db:create
    #   shell: bash
    #   env:
    #     MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    #   run: |
    #     docker-compose exec -T web rails db:create
        
    # - name: Run RSpec
    #   shell: bash
    #   env:
    #     RAILS_ENV: test
    #   run:  |
    #     docker-compose exec -T web rspec
    steps:
    - name: Run Jest
      shell: bash
      run: |
        docker-compose exec -T front npm run test