name: Ruby
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      shell: bash
      run: |
        docker-compose build
        docker-compose run -e RAILS_ENV=test web rails db:create
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD}}
    - name: Run RSpec
      shell: bash
      run:  |
        docker-compose run web rspec
      env:
        RAILS_ENV: test