name: CD
on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: [completed]
jobs:
  ecs_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: aws authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name : ecr login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: build and push
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker-compose build
          docker image tag nurse_app_web $ECR_REGISTRY/api:latest
          docker image tag nurse_app_front $ECR_REGISTRY/front:latest
          docker push $ECR_REGISTRY/api:latest
          docker push $ECR_REGISTRY/front:latest
      - name: sleep
        run: sleep 10
      - name: update service
        run: |
          aws ecs update-service --cluster cluster --service api_container --force-new-deployment
          aws ecs update-service --cluster cluster --service front_container --force-new-deployment